version: '3'

networks:
  django-rede:
    driver: bridge

services:
  db:
    image: mysql:5.7.22
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: pf1234
      MYSQL_USER: rafael
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: db
    ports:
      - "3308:3306"
    networks:
      - django-rede

  web:
    build: .
    environment:
      NAME_DB: db
      USER_DB: rafael
      PASSWORD_DB: 1234
      HOST_DB: db
      PORT_DB: 3306
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/core
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - django-rede